=== mmbase/mmbase/src/org/mmbase/framework/resources/component.xsd
<?xml version="1.0"?>
<!--
  @version $Id : $
-->
<xsd:schema
    xmlns="http://www.mmbase.org/xmlns/component"
    targetNamespace="http://www.mmbase.org/xmlns/component"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    version="1.0"
    >

  <xsd:import
      namespace="http://www.w3.org/XML/1998/namespace"
      schemaLocation="http://www.w3.org/2001/03/xml.xsd"
      />

  <xsd:element name="component">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="class" minOccurs="0" maxOccurs="1" />
        <xsd:element ref="description" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="block" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:Name" />
      <xsd:attribute name="defaultblock" type="xsd:IDREF" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="description">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="class">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="param" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:simpleContent>
              <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:Name" use="required"/>
              </xsd:extension>
            </xsd:simpleContent>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="name" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="block">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="description" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element name="head"    type="RendererType"  minOccurs="0" maxOccurs="1" />
        <xsd:element name="body"    type="RendererType"  minOccurs="0" maxOccurs="1" />
        <xsd:element name="process" type="RendererType"  minOccurs="0" maxOccurs="1" />
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:ID" />
      <xsd:attribute name="mimetype" type="xsd:token" />
      <xsd:attribute name="classification" type="xsd:token" />
      <xsd:attribute name="windowstate">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string" default="normal">
            <xsd:enumeration value="maximized" />
            <xsd:enumeration value="minimized" />
            <xsd:enumeration value="normal" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="RendererType">
    <xsd:sequence>
      <xsd:element ref="class" minOccurs="0" maxOccurs="1" />
      <xsd:element name="param" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:attribute name="name" type="xsd:Name" use="required" />
          <xsd:attribute name="type" type="xsd:token" />
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="jsp" type="xsd:token" />
  </xsd:complexType>

</xsd:schema>

=== mmbase/mmbase/contributions/calendar/src/main/config/components/calendar.xml
<?xml version="1.0" encoding="UTF-8"?>
<component
    name="calendar"
    defaultblock="months"
    version="1"
    xmlns="http://www.mmbase.org/xmlns/component"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mmbase.org/xmlns/component 
                        http://www.mmbase.org/xmlns/component.xsd">

  <class name="org.mmbase.framework.BasicComponent">  </class>
  <description xml:lang="nl">Tools voor agenda's</description>
  <description xml:lang="en">Tools for a calendar</description>
  <!--
      No dependencies.
  -->

  <title xml:lang="nl">MMBase kalender</title>
  <title xml:lang="en">MMBase calendar</title>

  <block name="months" 
    classification="mmbase.calendar"
    mimetype="text/html">
    <head jsp="head.jspx" />
    <body jsp="index.jspx">
      <param name="offset" />
    </body>
  </block>

</component>
