=== mmbase/mmbase/mmbase/trunk/config/default/dtd/wizard-schema_1_0.dtd
<!ELEMENT action ( object | relation )* >
<!ATTLIST action type NMTOKEN #REQUIRED >

<!ELEMENT command ( prompt?, search-filter* ) >
<!ATTLIST command name NMTOKEN #REQUIRED >
<!ATTLIST command age NMTOKEN #IMPLIED >
<!ATTLIST command fields CDATA #IMPLIED >
<!ATTLIST command filterrequired NMTOKEN #IMPLIED >
<!ATTLIST command inline NMTOKEN #IMPLIED >
<!ATTLIST command nodepath CDATA #IMPLIED >
<!ATTLIST command objectnumber NMTOKEN #IMPLIED >
<!ATTLIST command wizardname CDATA #IMPLIED >
<!ATTLIST command orderby CDATA #IMPLIED >
<!ATTLIST command command NMTOKEN #IMPLIED >
<!ATTLIST command startnodes CDATA #IMPLIED >

<!ELEMENT default ( #PCDATA ) >

<!ELEMENT field ( #PCDATA | optionlist | prompt | prefix | postfix )* >
<!ATTLIST field dtmaxlength NMTOKEN #IMPLIED >
<!ATTLIST field dtminlength NMTOKEN #IMPLIED >
<!ATTLIST field dtrequired NMTOKEN #IMPLIED >
<!ATTLIST field fdatapath CDATA #IMPLIED >
<!ATTLIST field ftype NMTOKEN #IMPLIED >
<!ATTLIST field name NMTOKEN #IMPLIED >
<!ATTLIST field rows NMTOKEN #IMPLIED >
<!ATTLIST field inline NMTOKEN #IMPLIED >
<!ATTLIST field wizardname CDATA #IMPLIED >

<!ELEMENT prefix ( #PCDATA ) >
<!ELEMENT postfix ( #PCDATA ) >

<!ELEMENT fieldset ( prompt?, field+ ) >

<!ELEMENT form-schema ( field | list | subtitle | title )* >
<!ATTLIST form-schema id NMTOKEN #IMPLIED >

<!ELEMENT item ( title | description | field | fieldset | list )* >
<!ATTLIST item displaytype NMTOKEN #IMPLIED >
<!ATTLIST item displaymode NMTOKEN #IMPLIED >

<!ELEMENT list ( title | description | action | command | item | title )* >
<!ATTLIST list maxoccurs CDATA #IMPLIED >
<!ATTLIST list minoccurs NMTOKEN #IMPLIED >
<!ATTLIST list extends CDATA #IMPLIED >
<!ATTLIST list fdatapath CDATA #IMPLIED >
<!ATTLIST list destination NMTOKEN #IMPLIED >
<!ATTLIST list hidecommand NMTOKEN #IMPLIED >
<!ATTLIST list orderby CDATA #IMPLIED >
<!ATTLIST list ordertype CDATA #IMPLIED >
<!ATTLIST list role NMTOKEN #IMPLIED >
<!ATTLIST list type NMTOKEN #IMPLIED >
<!ATTLIST list fields CDATA #IMPLIED >

<!ELEMENT lists ( optionlist ) >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT object ( field | relation )* >
<!ATTLIST object type NMTOKEN #IMPLIED >

<!ELEMENT query EMPTY >
<!ATTLIST query xpath CDATA #REQUIRED >

<!ELEMENT option ( #PCDATA ) >
<!ATTLIST option id NMTOKEN #REQUIRED >

<!ELEMENT optionlist ( option* | query ) >
<!ATTLIST optionlist name NMTOKEN #IMPLIED >
<!ATTLIST optionlist select NMTOKEN #IMPLIED >
<!ATTLIST optionlist optionid CDATA #IMPLIED >
<!ATTLIST optionlist optioncontent CDATA #IMPLIED >

<!ELEMENT prompt ( #PCDATA ) >

<!ELEMENT relation ( field | object )* >
<!ATTLIST relation destination CDATA #IMPLIED >
<!ATTLIST relation destinationtype NMTOKEN #IMPLIED >
<!ATTLIST relation role NMTOKEN #IMPLIED >

<!ELEMENT search-fields ( #PCDATA ) >

<!ELEMENT search-filter ( name, search-fields, default? ) >

<!ELEMENT subtitle ( #PCDATA ) >

<!ELEMENT title ( #PCDATA ) >

<!ELEMENT description ( #PCDATA ) >

<!ELEMENT wizard-schema ( title, action+, lists?, form-schema+ ) >
<!ATTLIST wizard-schema id NMTOKEN #IMPLIED >

=== mmbase/mmbase/mmbase/trunk/contributions/CMSContainer/cmsc/contentrepository/src/webapp/editors/config/contentelement/search_contentchannel_contentrel_contentelement.xml
<?xml version="1.0"?>
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list role="contentrel" destination="contentelement" minoccurs="0" maxoccurs="*"
	orderby="field[@name='pos']" ordertype="number">
	<title xml:lang="nl">Content element</title>
	<title xml:lang="en">Content element</title>
	<title xml:lang="zh">内容元素</title>

	<item>
		<field ftype="data" name="title">
			<prompt xml:lang="en">Title</prompt>
			<prompt xml:lang="nl">Titel</prompt>
			<prompt xml:lang="zh">标题</prompt>
		</field>
	</item>
	
	<command name="search" nodepath="contentelement" age="-1"
		fields="title,description,source,editor_note">
		<prompt xml:lang="en">Search content element</prompt>
		<prompt xml:lang="nl">Zoek content element</prompt>
		<prompt xml:lang="zh">查找内容元素</prompt>
		<search-filter>
			<name xml:lang="en">Title contains</name>
			<name xml:lang="nl">Titel bevat</name>
			<name xml:lang="zh">标题包含</name>
			<search-fields>[title]</search-fields>
		</search-filter>
		<search-filter>
			<name xml:lang="en">Description contains</name>
			<name xml:lang="nl">Omschrijving bevat</name>
			<name xml:lang="zh">描述包含</name>
			<search-fields>[description]</search-fields>
		</search-filter>
		<search-filter>
			<name xml:lang="en">Source contains</name>
			<name xml:lang="nl">Bronvermelding bevat</name>
			<name xml:lang="zh">资源包含</name>
			<search-fields>[source]</search-fields>
		</search-filter>
		<search-filter>
			<name xml:lang="en">Note contains</name>
			<name xml:lang="nl">Notitie bevat</name>
			<name xml:lang="zh">注释包含</name>
			<search-fields>[editor_note]</search-fields>
		</search-filter>
	</command>

	<action type="create">
		<relation destinationtype="contentelement" role="contentrel">
			<field name="pos">{sum(//relation[@role='contentrel' and @lastitem='true']/object[@type='contentelement']/../field[@name='pos'])+{$pos}}</field>
		</relation>
	</action>
</list>

=== mmbase/mmbase/mmbase/trunk/speeltuin/gomez/zagyg/edit/tasks/categories/subtopic_create.xml
<?xml version="1.0"?>
<!DOCTYPE wizard-schema PUBLIC "-//MMBase//DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<wizard-schema id="_create">
  <title xml:lang="nl">Topics</title>

  <action type="create">
    <object type="categories">
      <field name="title" />
      <field name="visible">1</field>
      <field name="end">4102441257</field>
    </object>
  </action>

  <lists include="tasks/sitestatlists.xml" />

  <form-schema extends="tasks/categories/schema.xml" id="basics" >

    <list include="tasks/categorytypes/list.xml" />

  </form-schema>
</wizard-schema>

=== mmbase/mmbase/mmbase/tags/v1_2_5/contributions/CMSContainer/cmsc/basicmodel/src/webapp/editors/config/option_lists/ImageCrop.xml
<?xml version="1.0"?>
<!DOCTYPE optionlist PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<optionlist name="ImageCrop">
   <option id="">
      <prompt xml:lang="nl">Niet afsnijden</prompt>
      <prompt xml:lang="en">Do not crop</prompt>
   </option>
   <option id="begin">
      <prompt xml:lang="nl">Begin</prompt>
      <prompt xml:lang="en">Begin</prompt>
   </option>
   <option id="middle">
      <prompt xml:lang="nl">Midden</prompt>
      <prompt xml:lang="en">Middle</prompt>
   </option>
   <option id="end">
      <prompt xml:lang="nl">Eind</prompt>
      <prompt xml:lang="en">End</prompt>
   </option>
</optionlist>

=== mmbase/mmbase/mmbase/tags/Root_with-mmbase-1-7-3/contributions/didactor2/src/education/templates/editwizards/data/config/attachment/attachments.xml
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list destination="attachments" role="related" minoccurs="0" maxoccurs="*">
    <title>Bijbehorende Bestanden</title>

    <item>
        <field name="title" ftype="data">
            <prompt>Titel</prompt>
        </field>
        <field ftype="data" name="description">
            <prompt>Omschrijving</prompt>
        </field>
        <field wizardname="config/attachment/attachment" ftype="startwizard" />
   </item>

    <command name="startwizard" inline="true" wizardname="config/attachment/attachment" objectnumber="new" />

    <command name="search" nodepath="attachments" fields="title" age="-1" orderby="number" directions="down" >
        <prompt>Zoeken naar bestand</prompt>
        <search-filter>
            <name>Titel bevat</name>
            <search-fields>title</search-fields>
        </search-filter>
        <search-filter>
            <name>Omschrijving bevat</name>
            <search-fields>description</search-fields>
        </search-filter>
    </command>

    <action type="create">
        <relation destinationtype="attachments" role="related" />
    </action>
</list>

=== mmbase/mmbase/mmbase/tags/joost-pre-2005-07-15/contributions/didactor2/src/education/templates/editwizards/data/list/positionedimages.xml
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list minoccurs="0" maxoccurs="*" ordertype="number" orderby="field[@name='pos']" role="posrel" destination="images">

    <title>Bijbehorende Afbeeldingen</title>

    <item>
        <field name="title" ftype="data">
            <prompt>Titel</prompt>
        </field>
        <field fdatapath="field[@name=&apos;pos&apos;]" ftype="line"><prompt>Positie</prompt></field>
        <field ftype="data" name="description">
            <prompt>Omschrijving</prompt>
        </field>
        <field ftype="image" name="title">
            <prompt>Afbeelding</prompt>
        </field>
        <field wizardname="image" ftype="startwizard" />
    </item>

    <command name="startwizard" inline="true" wizardname="image" objectnumber="new" />

    <command name="search" nodepath="images" fields="title" age="-1" orderby="number" directions="down" >
        <prompt>Zoeken naar afbeeldingen</prompt>
        <search-filter>
            <name>Titel bevat</name>
            <search-fields>title</search-fields>
        </search-filter>
        <search-filter>
            <name>Omschrijving bevat</name>
            <search-fields>description</search-fields>
        </search-filter>
    </command>

    <action type="create">
        <relation role="posrel" destinationtype="images">
              <field name="pos">{sum(//relation[@role='posrel' and @lastitem='true']/field[@name='pos'])+{$pos}}</field>
        </relation>
    </action>

</list>

=== mmbase/mmbase/mmbase/tags/v1_4_3/contributions/CMSContainer/cmsc/basicmodel/src/webapp/editors/config/option_lists/ImageCrop.xml
<?xml version="1.0"?>
<!DOCTYPE optionlist PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<optionlist name="ImageCrop">
   <option id="">
      <prompt xml:lang="nl">Niet afsnijden</prompt>
      <prompt xml:lang="en">Do not crop</prompt>
	  <prompt xml:lang="zh">不裁切</prompt>
   </option>
   <option id="begin">
      <prompt xml:lang="nl">Begin</prompt>
      <prompt xml:lang="en">Begin</prompt>
	  <prompt xml:lang="zh">开始</prompt>
   </option>
   <option id="middle">
      <prompt xml:lang="nl">Midden</prompt>
      <prompt xml:lang="en">Middle</prompt>
	  <prompt xml:lang="zh">中间</prompt>
   </option>
   <option id="end">
      <prompt xml:lang="nl">Eind</prompt>
      <prompt xml:lang="en">End</prompt>
	  <prompt xml:lang="zh">终止</prompt>
   </option>
</optionlist>

=== mmbase/mmbase/mmbase/tags/v1_5_3/contributions/CMSContainer_Portlets/portlets-dynamicforms/src/webapp/editors/config/responseform/responseform.xml
<?xml version="1.0"?>
<!DOCTYPE wizard-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<wizard-schema id="responseform">
   <title xml:lang="nl">Dynamisch formulier</title>
   <title xml:lang="en">Dynamic form</title>
   <title xml:lang="zh">动态表单</title>
   <action include="config/responseform/create_responseform.xml" />
   <action include="config/responseform/delete_responseform.xml" />
   <action include="config/responseform/load_responseform.xml" />

   <lists>
      <optionlist include="config/option_lists/boolean.xml" />
      <optionlist include="config/option_lists/inputtypes.xml" />
   </lists>

   <steps>
      <step form-schema="edit_responseform" />
   </steps>

   <form-schema id="edit_responseform" extends="config/responseform/edit_responseform.xml" />
</wizard-schema>

=== mmbase/mmbase/mmbase/tags/bouwradius-release-2005-08-11/contributions/didactor2/src/education/templates/editwizards/data/config/flashpages/flashpages-described.xml
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list role="descriptionrel" destinationtype="flashpages"  minoccurs="0" maxoccurs="*" searchdir="both"> 
    <title>Bijbehorende flash paginas</title>
    <item>
        <field name="name" ftype="data">
            <prompt>Naam</prompt>
            <description>Naam van de flashpagina</description>
        </field>
        <field fdatapath="field[@name='description']" ftype="line"><prompt>Omschrijving van de link</prompt></field> 
        <field wizardname="config/flashpages/flashpages" ftype="startwizard" />
    </item>

    <action type="create">
        <relation role="descriptionrel" destinationtype="flashpages">
        </relation>
    </action>

    <command name="startwizard" inline="true" wizardname="config/flashpages/flashpages" objectnumber="new">
      <prompt>Nieuwe flash pagina
      </prompt>
    </command>
     <command name="search" nodepath="flashpages" fields="name" age="-1" orderby="number" directions="down" >
        <prompt>Zoeken naar flash paginas</prompt>
        <search-filter>
            <name>Naam bevat</name>
            <search-fields>name</search-fields>
        </search-filter>
   </command>
</list>
