=== mmbase/mmbase/mmbase/trunk/config/default/dtd/wizard-schema_1_0.dtd
<!ELEMENT action ( object | relation )* >
<!ATTLIST action type NMTOKEN #REQUIRED >

<!ELEMENT command ( prompt?, search-filter* ) >
<!ATTLIST command name NMTOKEN #REQUIRED >
<!ATTLIST command age NMTOKEN #IMPLIED >
<!ATTLIST command fields CDATA #IMPLIED >
<!ATTLIST command filterrequired NMTOKEN #IMPLIED >
<!ATTLIST command inline NMTOKEN #IMPLIED >
<!ATTLIST command nodepath CDATA #IMPLIED >
<!ATTLIST command objectnumber NMTOKEN #IMPLIED >
<!ATTLIST command wizardname CDATA #IMPLIED >
<!ATTLIST command orderby CDATA #IMPLIED >
<!ATTLIST command command NMTOKEN #IMPLIED >
<!ATTLIST command startnodes CDATA #IMPLIED >

<!ELEMENT default ( #PCDATA ) >

<!ELEMENT field ( #PCDATA | optionlist | prompt | prefix | postfix )* >
<!ATTLIST field dtmaxlength NMTOKEN #IMPLIED >
<!ATTLIST field dtminlength NMTOKEN #IMPLIED >
<!ATTLIST field dtrequired NMTOKEN #IMPLIED >
<!ATTLIST field fdatapath CDATA #IMPLIED >
<!ATTLIST field ftype NMTOKEN #IMPLIED >
<!ATTLIST field name NMTOKEN #IMPLIED >
<!ATTLIST field rows NMTOKEN #IMPLIED >
<!ATTLIST field inline NMTOKEN #IMPLIED >
<!ATTLIST field wizardname CDATA #IMPLIED >

<!ELEMENT prefix ( #PCDATA ) >
<!ELEMENT postfix ( #PCDATA ) >

<!ELEMENT fieldset ( prompt?, field+ ) >

<!ELEMENT form-schema ( field | list | subtitle | title )* >
<!ATTLIST form-schema id NMTOKEN #IMPLIED >

<!ELEMENT item ( title | description | field | fieldset | list )* >
<!ATTLIST item displaytype NMTOKEN #IMPLIED >
<!ATTLIST item displaymode NMTOKEN #IMPLIED >

<!ELEMENT list ( title | description | action | command | item | title )* >
<!ATTLIST list maxoccurs CDATA #IMPLIED >
<!ATTLIST list minoccurs NMTOKEN #IMPLIED >
<!ATTLIST list extends CDATA #IMPLIED >
<!ATTLIST list fdatapath CDATA #IMPLIED >
<!ATTLIST list destination NMTOKEN #IMPLIED >
<!ATTLIST list hidecommand NMTOKEN #IMPLIED >
<!ATTLIST list orderby CDATA #IMPLIED >
<!ATTLIST list ordertype CDATA #IMPLIED >
<!ATTLIST list role NMTOKEN #IMPLIED >
<!ATTLIST list type NMTOKEN #IMPLIED >
<!ATTLIST list fields CDATA #IMPLIED >

<!ELEMENT lists ( optionlist ) >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT object ( field | relation )* >
<!ATTLIST object type NMTOKEN #IMPLIED >

<!ELEMENT query EMPTY >
<!ATTLIST query xpath CDATA #REQUIRED >

<!ELEMENT option ( #PCDATA ) >
<!ATTLIST option id NMTOKEN #REQUIRED >

<!ELEMENT optionlist ( option* | query ) >
<!ATTLIST optionlist name NMTOKEN #IMPLIED >
<!ATTLIST optionlist select NMTOKEN #IMPLIED >
<!ATTLIST optionlist optionid CDATA #IMPLIED >
<!ATTLIST optionlist optioncontent CDATA #IMPLIED >

<!ELEMENT prompt ( #PCDATA ) >

<!ELEMENT relation ( field | object )* >
<!ATTLIST relation destination CDATA #IMPLIED >
<!ATTLIST relation destinationtype NMTOKEN #IMPLIED >
<!ATTLIST relation role NMTOKEN #IMPLIED >

<!ELEMENT search-fields ( #PCDATA ) >

<!ELEMENT search-filter ( name, search-fields, default? ) >

<!ELEMENT subtitle ( #PCDATA ) >

<!ELEMENT title ( #PCDATA ) >

<!ELEMENT description ( #PCDATA ) >

<!ELEMENT wizard-schema ( title, action+, lists?, form-schema+ ) >
<!ATTLIST wizard-schema id NMTOKEN #IMPLIED >

=== mmbase/mmbase/mmbase/tags/Didactor-2_1_0/contributions/didactor2/src/education/templates/editwizards/data/config/htmlpages/htmlpages.xml
<?xml version="1.0"?>
<!DOCTYPE wizard-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<wizard-schema id="empty">
    <title>HTML Pagina Editor</title>


    <action type="create">
       <object type="htmlpages">
           <field name="showtitle">1</field>
       </object>
    </action>


    <action type="load"/>

    <action type="delete" />


    <lists>
       <optionlist include="config/option_list/boolean.xml" />
    </lists>


    <form-schema id="step1">
       <title>Pagina invoeren</title>
       <field name="name" >
          <prompt xml:lang="en">Name</prompt>
          <prompt xml:lang="nl">Naam</prompt>
       </field>

       <field name="showtitle" ftype="enum">
          <prompt xml:lang="en">Show title</prompt>
          <prompt xml:lang="nl">Titel laten zien</prompt>
          <optionlist select="boolean" />
       </field>

       <field name="content" ftype="html" dtminlength="0">
          <prompt xml:lang="en">Content</prompt>
          <prompt xml:lang="nl">Content</prompt>
       </field>
    </form-schema>

</wizard-schema>

=== mmbase/mmbase/mmbase/tags/release-2005-07-15-baronie-only/contributions/didactor2/src/education/templates/editwizards/data/config/learnobject/learnobjects.xml
<?xml version="1.0"?>
<!DOCTYPE wizard-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<wizard-schema id="empty">
    <title>Leerobject Editor</title>

    <action type="create">
        <object type="learnobjects">
            <field name="showtitle">1</field>
        </object>
    </action>
    
    <action type="load">
        <relation destination="mmevents" role="related" />
        <relation destination="competencies" role="needcomp" />
        <relation destination="competencies" role="developcomp" />
    </action>

    <action type="delete" />
    
    <lists>
       <optionlist include="option_lists/boolean.xml" />
   </lists>

    <steps>
        <step form-schema="step1" />
        <step form-schema="step2" />
    </steps>

    <form-schema id="step1">
        <title>Leerobject invoeren</title>
        <field name="name" >
            <prompt>Naam</prompt>
        </field>

      <field name="showtitle" ftype="enum">
         <prompt xml:lang="nl">Titel laten zien</prompt>
         <prompt xml:lang="en">Show title</prompt>
         <optionlist select="boolean" />
      </field>
 

        <field name="intro" ftype="html" dtminlength="0">
            <prompt>Tekst</prompt>
        </field>

        <list role="related" extends="config/online/online-list.xml" />
    </form-schema>

    <form-schema id="step2">
        <title>Competenties invoeren</title>
        <field name="name" ftype="data"/>
        <list extends="config/competency/needcompetencies-list.xml"/>
        <list extends="config/competency/developcompetencies-list.xml"/>
    </form-schema>

</wizard-schema>

=== mmbase/mmbase/mmbase/tags/v1_4_14/contributions/CMSContainer_Modules/tasks/src/webapp/editors/config/task/task.xml
<?xml version="1.0"?>
<!DOCTYPE wizard-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<wizard-schema id="task">

   <title xml:lang="nl">Taak</title>
   <title xml:lang="en">Task</title>
   <action include="config/task/create_task.xml"/>
   <action include="config/task/delete_task.xml"/>
   <action include="config/task/load_task.xml"/>

   <lists>
      <optionlist include="config/task/taskstatus.xml" />
   </lists>

   <steps>
      <step form-schema="edit_task"/>
   </steps>
   <form-schema id="edit_task" extends="config/task/edit_task.xml"/>
</wizard-schema>
