=== mmbase/mmbase/mmbase/trunk/config/default/dtd/wizard-schema_1_0.dtd
<!ELEMENT action ( object | relation )* >
<!ATTLIST action type NMTOKEN #REQUIRED >

<!ELEMENT command ( prompt?, search-filter* ) >
<!ATTLIST command name NMTOKEN #REQUIRED >
<!ATTLIST command age NMTOKEN #IMPLIED >
<!ATTLIST command fields CDATA #IMPLIED >
<!ATTLIST command filterrequired NMTOKEN #IMPLIED >
<!ATTLIST command inline NMTOKEN #IMPLIED >
<!ATTLIST command nodepath CDATA #IMPLIED >
<!ATTLIST command objectnumber NMTOKEN #IMPLIED >
<!ATTLIST command wizardname CDATA #IMPLIED >
<!ATTLIST command orderby CDATA #IMPLIED >
<!ATTLIST command command NMTOKEN #IMPLIED >
<!ATTLIST command startnodes CDATA #IMPLIED >

<!ELEMENT default ( #PCDATA ) >

<!ELEMENT field ( #PCDATA | optionlist | prompt | prefix | postfix )* >
<!ATTLIST field dtmaxlength NMTOKEN #IMPLIED >
<!ATTLIST field dtminlength NMTOKEN #IMPLIED >
<!ATTLIST field dtrequired NMTOKEN #IMPLIED >
<!ATTLIST field fdatapath CDATA #IMPLIED >
<!ATTLIST field ftype NMTOKEN #IMPLIED >
<!ATTLIST field name NMTOKEN #IMPLIED >
<!ATTLIST field rows NMTOKEN #IMPLIED >
<!ATTLIST field inline NMTOKEN #IMPLIED >
<!ATTLIST field wizardname CDATA #IMPLIED >

<!ELEMENT prefix ( #PCDATA ) >
<!ELEMENT postfix ( #PCDATA ) >

<!ELEMENT fieldset ( prompt?, field+ ) >

<!ELEMENT form-schema ( field | list | subtitle | title )* >
<!ATTLIST form-schema id NMTOKEN #IMPLIED >

<!ELEMENT item ( title | description | field | fieldset | list )* >
<!ATTLIST item displaytype NMTOKEN #IMPLIED >
<!ATTLIST item displaymode NMTOKEN #IMPLIED >

<!ELEMENT list ( title | description | action | command | item | title )* >
<!ATTLIST list maxoccurs CDATA #IMPLIED >
<!ATTLIST list minoccurs NMTOKEN #IMPLIED >
<!ATTLIST list extends CDATA #IMPLIED >
<!ATTLIST list fdatapath CDATA #IMPLIED >
<!ATTLIST list destination NMTOKEN #IMPLIED >
<!ATTLIST list hidecommand NMTOKEN #IMPLIED >
<!ATTLIST list orderby CDATA #IMPLIED >
<!ATTLIST list ordertype CDATA #IMPLIED >
<!ATTLIST list role NMTOKEN #IMPLIED >
<!ATTLIST list type NMTOKEN #IMPLIED >
<!ATTLIST list fields CDATA #IMPLIED >

<!ELEMENT lists ( optionlist ) >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT object ( field | relation )* >
<!ATTLIST object type NMTOKEN #IMPLIED >

<!ELEMENT query EMPTY >
<!ATTLIST query xpath CDATA #REQUIRED >

<!ELEMENT option ( #PCDATA ) >
<!ATTLIST option id NMTOKEN #REQUIRED >

<!ELEMENT optionlist ( option* | query ) >
<!ATTLIST optionlist name NMTOKEN #IMPLIED >
<!ATTLIST optionlist select NMTOKEN #IMPLIED >
<!ATTLIST optionlist optionid CDATA #IMPLIED >
<!ATTLIST optionlist optioncontent CDATA #IMPLIED >

<!ELEMENT prompt ( #PCDATA ) >

<!ELEMENT relation ( field | object )* >
<!ATTLIST relation destination CDATA #IMPLIED >
<!ATTLIST relation destinationtype NMTOKEN #IMPLIED >
<!ATTLIST relation role NMTOKEN #IMPLIED >

<!ELEMENT search-fields ( #PCDATA ) >

<!ELEMENT search-filter ( name, search-fields, default? ) >

<!ELEMENT subtitle ( #PCDATA ) >

<!ELEMENT title ( #PCDATA ) >

<!ELEMENT description ( #PCDATA ) >

<!ELEMENT wizard-schema ( title, action+, lists?, form-schema+ ) >
<!ATTLIST wizard-schema id NMTOKEN #IMPLIED >

=== mmbase/mmbase/mmbase/tags/release-2005-01-07/contributions/didactor2/src/education/templates/editwizards/data/schemas/urls.xml
<?xml version="1.0"?>
<!DOCTYPE form-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">

    <form-schema>
        <title>URLs</title>
     <list role="related" extends="list/urls.xml" />
 
        <!-- we need a new list because there can be only one search command per list -->
        <list minoccurs="0" maxoccurs="*" role="related">
            <title>Zoeken op tekenreeks</title>
            <item displaytype="none"></item>
 
            <action type="create">
                <relation role="related" destinationtype="urls"/>
            </action>


             <command name="search" nodepath="metalangstring,metadata,urls" fields="urls.name,metalangstring.value" age="7" orderby="urls.number" directions="down" >
                <prompt>Zoeken op metadata</prompt>
                <search-filter>
                    <name>Metadata tekenreeks bevat</name>
                    <search-fields>metalangstring.value</search-fields>
                </search-filter>
           </command>           
        </list>

        <!-- we need a new list because there can be only one search command per list -->
        <list minoccurs="0" maxoccurs="*" role="related">
            <title>Zoeken op vocabulair</title>
            <item displaytype="none"></item>
 
            <action type="create">
                <relation role="related" destinationtype="urls"/>
            </action>


             <command name="search" nodepath="metavocabulary,metadata,urls" fields="urls.name,metavocabulary.value" age="7" orderby="urls.number" directions="down" >
                <prompt>Zoeken op metadata</prompt>
                <search-filter>
                    <name>Metadata vocabulair bevat</name>
                    <search-fields>metavocabulary.value</search-fields>
                </search-filter>
           </command>
           
        </list>

        <!-- we need a new list because there can be only one search command per list -->
        <list minoccurs="0" maxoccurs="*" ordertype="number" role="related">
            <title>Zoeken op datum (YYYY-MM-DD HH:MM:SS)</title>
            <item displaytype="none"></item>
 
            <action type="create">
                <relation role="posrel" destinationtype="urls"/>
            </action>


             <command name="search" nodepath="metadate,metadata,urls" fields="urls.name,metadate.value" age="7" orderby="urls.number" directions="down" >
                <prompt>Zoeken naar leerobjecten op metadata</prompt>
                <search-filter>
                    <name>Metadata datum bevat</name>
                    <search-fields>FROM_UNIXTIME(metadate.value)</search-fields>
                </search-filter>
           </command>
           
        </list>
 


    </form-schema>

=== mmbase/mmbase/mmbase/trunk/contributions/didactor2/src/education/templates/editwizards/data/config/tips/tips-described.xml
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list role="descriptionrel" destinationtype="flashpages"  minoccurs="0" maxoccurs="*" searchdir="both"> 
    <title>Bijbehorende tips </title>
    <item>
        <field name="name" ftype="data">
            <prompt>Naam</prompt>
            <description>Naam van de tips</description>
        </field>
        <field fdatapath="field[@name='description']" ftype="line"><prompt>Omschrijving van de link</prompt></field> 
        <field wizardname="config/tips/tips" ftype="startwizard" />
    </item>

    <action type="create">
        <relation role="descriptionrel" destinationtype="tips">
        </relation>
    </action>

    <command name="startwizard" inline="true" wizardname="config/tips/tips" objectnumber="new">
      <prompt></prompt>
    </command>
     <command name="search" nodepath="tips" fields="name" age="-1" orderby="number" directions="down" >
        <prompt>Zoeken naar tips</prompt>
        <search-filter>
            <name>Naam bevat</name>
            <search-fields>name</search-fields>
        </search-filter>
   </command>
</list>

=== mmbase/mmbase/mmbase/tags/Didactor-2_3_0_beta_2008week47/contributions/didactor2/src/education/templates/editwizards/data/config/pdf/pdf-described.xml
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list role="descriptionrel" destinationtype="pdf"  minoccurs="0" maxoccurs="*" searchdir="both"> 
    <title>Bijbehorende documenten</title>
    <item>
        <field name="name" ftype="data">
            <prompt>Naam</prompt>
            <description>Naam van de pdf</description>
        </field>
        <field fdatapath="field[@name='description']" ftype="line"><prompt>Omschrijving van de link</prompt></field> 
        <field wizardname="config/pdf/pdf" ftype="startwizard" />
    </item>

    <action type="create">
        <relation role="descriptionrel" destinationtype="pdf">
        </relation>
    </action>

    <command name="startwizard" inline="true" wizardname="config/pdf/pdf" objectnumber="new">
    </command>
     <command name="search" nodepath="pdf" fields="name" age="-1" orderby="number" directions="down" >
        <prompt>Zoeken naar pdf</prompt>
        <search-filter>
            <name>Naam bevat</name>
            <search-fields>name</search-fields>
        </search-filter>
   </command>
</list>

=== mmbase/mmbase/mmbase/tags/v1_3_5/contributions/CMSContainer/cmsc/sitemanagement/src/webapp/editors/config/page/load_page.xml
<?xml version="1.0"?>
<!DOCTYPE action PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<action type="load">
	<field name="creationdate" />
	<field name="lastmodifieddate" />
	<field name="publishdate" />
	<field name="expiredate" />
	<field name="lastmodifier" />
	<field name="use_expirydate" />
	<field name="urlfragment" />
	<field name="title" />
	<field name="description" />
	<field name="inmenu" />
	<field name="secure" />
	<field name="externalurl"/>
	
	<relation destination="images" role="namedrel" />
	<relation destination="layout" role="allowrel" />
	<relation destination="layout" role="layoutrel" />
	<relation destination="page" role="navrel" />
	<relation destination="portlet" role="portletrel" />
	<relation destination="stylesheet" role="allowrel" />
	<relation destination="stylesheet" role="stylerel" />
</action>

=== mmbase/mmbase/mmbase/tags/release-2005-06-17/contributions/didactor2/src/education/templates/editwizards/data/competencies.xml
<?xml version="1.0"?>
<!DOCTYPE wizard-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<wizard-schema id="competencies">
   <title xml:lang="nl">Competentie editor</title>
   <title xml:lang="en">Competence editor</title>

   <action type="create">
      <object type="competencies">
      </object>
   </action>
   <action type="delete">
      <prompt>Weet u zeker dat u deze competentie wilt verwijderen ?</prompt>
      <description>Klik hier om deze competentie te verwijderen.</description>
   </action>
   <action type="load">
      <relation destination="tests" role="comprel">
         <object type="tests">
            <field name="name"/>
         </object>
      </relation>
      <relation destination="competencetypes" role="posrel">
         <object type="competencetypes">
            <field name="name"/>
         </object>
      </relation>
   </action>

   <lists>
   </lists>

   <steps>
      <step form-schema="edit_competencies"/>
   </steps>

<form-schema id="edit_competencies">
   <field name="name" dtminlength="0" dtmaxlength="255">
   <prompt>naam</prompt></field>

   <list role="comprel" destination="tests" minoccurs="0" maxoccurs="*" ordertype="number">
      <title>Bijbehorende testen</title>
      <item>
         <field name="name" ftype="data"/>
         <field ftype="startwizard" wizardname="tests" />
      </item>
      <command name="search" nodepath="tests" fields="name" age="-1" orderby="number" directions="down">
         <search-filter>
            <name>Naam bevat</name>
            <search-fields>name</search-fields>
         </search-filter>
      </command>
      <command name="startwizard" inline="true" wizardname="tests" objectnumber="new">
         <prompt>Nieuw</prompt>
      </command>

      <action type="create">
         <relation destinationtype="tests" role="comprel">
         </relation>
      </action>
   </list>


   <list role="posrel" destination="competencetypes" minoccurs="1" maxoccurs="1" ordertype="number">
      <title xml:lang="nl">Competentie type</title>
      <title xml:lang="en">Competence type</title>
      <item>
         <field name="name" ftype="data"/>
         <field ftype="startwizard" wizardname="competencetypes" />
      </item>
      <command name="search" nodepath="competencetypes" fields="name" age="-1" orderby="number" directions="down">
         <search-filter>
            <name xml:lang="nl">Naam bevat</name>
            <name xml:lang="en">Name</name>
            <search-fields>name</search-fields>
         </search-filter>
      </command>
      <command name="startwizard" inline="true" wizardname="competencetypes" objectnumber="new">
         <prompt xml:lang="nl">Nieuw</prompt>
         <prompt xml:lang="en">New</prompt>
      </command>

      <action type="create">
         <relation destinationtype="competencetypes" role="posrel"/>
      </action>
   </list>


</form-schema>
</wizard-schema>

=== mmbase/mmbase/mmbase/tags/release-2005-05-27/contributions/didactor2/src/education/templates/editwizards/data/list/audiotapes-posrel.xml
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list destination="audiotapes" role="posrel" minoccurs="0" maxoccurs="*" ordertype="number" orderby="field[@name='pos']">
    <title>Bijbehorende Audio</title>

    <item>
        <field name="title" ftype="data">
            <prompt>Titel</prompt>
        </field>
        <field ftype="data" name="intro">
            <prompt>Omschrijving</prompt>
        </field>
       <field wizardname="audiotape" ftype="startwizard" />
   </item>

    <command name="startwizard" inline="true" wizardname="audiotape" objectnumber="new" />

    <command name="search" nodepath="audiotapes" fields="title" age="-1" orderby="number" directions="down" >
        <prompt>Zoeken naar audio</prompt>
        <search-filter>
            <name>Titel bevat</name>
            <search-fields>title</search-fields>
        </search-filter>
        <search-filter>
            <name>Omschrijving bevat</name>
            <search-fields>intro</search-fields>
        </search-filter>
    </command>

    <action type="create">
        <relation destinationtype="audiotapes" role="posrel">
          <field name="pos">{sum(//relation[@role='posrel' and @lastitem='true']/field[@name='pos'])+{$pos}}</field>
        </relation>
   </action>
</list>

=== mmbase/mmbase/mmbase/tags/v1_6_1/contributions/CMSContainer/cmsc/basicmodel/src/webapp/editors/config/attachments/search_newsletter_posrel_attachments.xml
<?xml version="1.0"?>
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list role="posrel" destination="attachments" minoccurs="0" maxoccurs="*"
   orderby="field[@name='pos']" ordertype="number">
   
   <title xml:lang="nl">Bijlage</title>
   <title xml:lang="en">Attachment</title>
   <title xml:lang="zh">附件</title>

   <item>
		<field name="title" ftype="data" dtrequired="true">
         <prompt xml:lang="en">Title</prompt>
         <prompt xml:lang="nl">Titel</prompt>
         <prompt xml:lang="zh">标题</prompt>
      </field>
		<field name="description" ftype="data" rows="3">
         <prompt xml:lang="en">Description</prompt>
         <prompt xml:lang="nl">Omschrijving</prompt>
         <prompt xml:lang="zh">描述</prompt>
      </field>
   <!-- These are not interesting to show
      <field name="filename">
         <prompt xml:lang="en">Filename</prompt>
         <prompt xml:lang="nl">Bestandsnaam</prompt>
         <prompt xml:lang="zh">文件名</prompt>
      </field>
      <field name="mimetype" ftype="data">
         <prompt xml:lang="en">Mimetype</prompt>
         <prompt xml:lang="nl">Mimetype</prompt>
         <prompt xml:lang="zh">Mime类型</prompt>
      </field>
      <field name="size" ftype="data">
         <prompt xml:lang="en">Size</prompt>
         <prompt xml:lang="nl">Grootte</prompt>
         <prompt xml:lang="zh">大小</prompt>
      </field>
    -->
      <field name="handle" ftype="filedata" dtmaxsize="16000000">
         <prompt xml:lang="en">Attachment</prompt>
         <prompt xml:lang="nl">Bijlage</prompt>
         <prompt xml:lang="zh">附件</prompt>
      </field>
   </item>

   <command name="siteassetsselector" nodepath="attachments" age="-1" fields="title,description">
      <prompt xml:lang="en">Search attachment</prompt>
      <prompt xml:lang="nl">Zoek bijlage</prompt>
      <prompt xml:lang="zh">查找附件</prompt>
      <search-filter>
         <name xml:lang="en">Title / Description</name>
         <name xml:lang="nl">Titel / Omschrijving</name>
         <name xml:lang="zh">标题包含 / 描述包含</name>
         <search-fields>[title]|[description]</search-fields>
      </search-filter>
      <search-filter>
         <name xml:lang="en">Title contains</name>
         <name xml:lang="nl">Titel bevat</name>
         <name xml:lang="zh">标题包含</name>
         <search-fields>[title]</search-fields>
      </search-filter>
      <search-filter>
         <name xml:lang="en">Description contains</name>
         <name xml:lang="nl">Omschrijving bevat</name>
         <name xml:lang="zh">描述包含</name>
         <search-fields>[description]</search-fields>
      </search-filter>
   </command>
   
   <command name="startwizard" inline="true" wizardname="config/attachments/attachments" objectnumber="new">
      <prompt xml:lang="en">New</prompt>
      <prompt xml:lang="nl">Nieuw</prompt>
      <prompt xml:lang="zh">新建</prompt>
   </command>

   <action type="create">
      <relation destinationtype="attachments" role="posrel">
         <field name="pos">{sum(//relation[@role='posrel' and @firstitem='true']/object[@type='attachments']/../field[@name='pos'])-{$pos}}</field>
      </relation>
   </action>
</list>

=== mmbase/mmbase/mmbase/tags/Didactor-2_3_0_beta_week25/contributions/didactor2/src/metadata/templates/editwizards/data/config/metalangstring/metalangstring.xml
<?xml version="1.0"?>
<!DOCTYPE wizard-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<wizard-schema id="empty">
  <title xml:lang="nl">Tekenreeks Editor</title>
  <title xml:lang="en">Langstring Editor</title>
  <action type="load">
  </action>

  <action type="create">
    <object type="metalangstring"/>
  </action>

  <steps>
    <step form-schema="step1" />
  </steps>

  <form-schema id="step1">
    <title xml:lang="nl">Metadata Invoeren</title>
    <title xml:lang="en">Metadata</title>
    <field name="value" ftype="line">
      <prompt xml:lang="nl">Waarde</prompt>
      <prompt xml:lang="en">Value</prompt>
    </field>
    <field name="language" ftype="line">
      <prompt xml:lang="nl">Taal van de bovenstaande waarde</prompt>
      <prompt xml:lang="en">Language of the value</prompt>
    </field>

    </form-schema>
</wizard-schema>
