=== mmbase/mmbase/config/default/dtd/wizard-schema_1_0.dtd
<!ELEMENT action ( object | relation )* >
<!ATTLIST action type NMTOKEN #REQUIRED >

<!ELEMENT command ( prompt?, search-filter* ) >
<!ATTLIST command name NMTOKEN #REQUIRED >
<!ATTLIST command age NMTOKEN #IMPLIED >
<!ATTLIST command fields NMTOKEN #IMPLIED >
<!ATTLIST command filterrequired NMTOKEN #IMPLIED >
<!ATTLIST command inline NMTOKEN #IMPLIED >
<!ATTLIST command nodepath NMTOKEN #IMPLIED >
<!ATTLIST command objectnumber NMTOKEN #IMPLIED >
<!ATTLIST command wizardname NMTOKEN #IMPLIED >
<!ATTLIST command orderby NMTOKEN #REQUIRED >

<!ELEMENT default ( #PCDATA ) >

<!ELEMENT field ( #PCDATA | optionlist | prompt )* >
<!ATTLIST field dtmaxlength NMTOKEN #IMPLIED >
<!ATTLIST field dtminlength NMTOKEN #IMPLIED >
<!ATTLIST field dtrequired NMTOKEN #IMPLIED >
<!ATTLIST field fdatapath CDATA #IMPLIED >
<!ATTLIST field ftype NMTOKEN #IMPLIED >
<!ATTLIST field name NMTOKEN #IMPLIED >
<!ATTLIST field rows NMTOKEN #IMPLIED >

<!ELEMENT fieldset ( field+, prompt ) >

<!ELEMENT form-schema ( field | list | subtitle | title )* >
<!ATTLIST form-schema id NMTOKEN #IMPLIED >

<!ELEMENT item ( title | field | fieldset )* >
<!ATTLIST item displaytype NMTOKEN #REQUIRED >

<!ELEMENT list ( title | action | command | item | title )* >
<!ATTLIST list maxoccurs CDATA #REQUIRED >
<!ATTLIST list minoccurs NMTOKEN #REQUIRED >
<!ATTLIST list extends CDATA #IMPLIED >
<!ATTLIST list fdatapath CDATA #IMPLIED >
<!ATTLIST list destination NMTOKEN #REQUIRED >
<!ATTLIST list hidecommand NMTOKEN #IMPLIED >
<!ATTLIST list orderby CDATA #REQUIRED >
<!ATTLIST list ordertype NMTOKEN #REQUIRED >
<!ATTLIST list role NMTOKEN #REQUIRED >
<!ATTLIST list type NMTOKEN #IMPLIED >

<!ELEMENT lists ( optionlist ) >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT object ( field )* >
<!ATTLIST object type NMTOKEN #REQUIRED >

<!ELEMENT option ( #PCDATA ) >
<!ATTLIST option id NMTOKEN #REQUIRED >

<!ELEMENT optionlist ( option* ) >
<!ATTLIST optionlist name NMTOKEN #IMPLIED >
<!ATTLIST optionlist select NMTOKEN #IMPLIED >

<!ELEMENT prompt ( #PCDATA ) >

<!ELEMENT relation ( field? | object? ) >
<!ATTLIST relation destination NMTOKEN #IMPLIED >
<!ATTLIST relation destinationtype NMTOKEN #IMPLIED >
<!ATTLIST relation role NMTOKEN #REQUIRED >

<!ELEMENT search-fields ( #PCDATA ) >

<!ELEMENT search-filter ( name, search-fields, default? ) >

<!ELEMENT subtitle ( #PCDATA ) >

<!ELEMENT title ( #PCDATA ) >

<!ELEMENT wizard-schema ( title, action+, lists?, form-schema+ ) >
<!ATTLIST wizard-schema id NMTOKEN #IMPLIED >

=== mmbase/mmbase/contributions/didactor2/src/education/templates/editwizards/data/config/people/people-list.xml
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list destination="people" role="classrel" minoccurs="0" maxoccurs="*" ordertype="string" orderby="lastname" hidecommand="move-up|move-down">
    <title>Bijbehorende Personen</title>
    <item>
        <field name="firstname" ftype="data">
            <prompt>Voornaam</prompt>
        </field>
        <field name="lastname" ftype="data">
            <prompt>Achternaam</prompt>
        </field>
        <list extends="config/role/roles-inlist.xml"/>
        <field wizardname="config/people/people" ftype="startwizard" />
    </item>

    <action type="create">
        <relation destinationtype="people" role="classrel">
        </relation>
    </action>

    <action type="add">
        <relation destinationtype="peope" role="classrel">
            <object type="people">
            </object>
        </relation>
    </action>

    <action type="load">
        <relation destinationtype="people" role="classrel">
            <object type="people">
              <relation destinationtype="roles" role="related">
                <object type="roles"/>
              </relation>
            </object>
        </relation>
    </action>

    <command name="startwizard" inline="true" wizardname="config/people/people" objectnumber="new" />

    <command name="search" nodepath="people" fields="firstname,lastname,username" age="-1" orderby="number" directions="down" >
        <prompt>Zoeken naar personen</prompt>
        <search-filter>
            <name>Achternaam bevat</name>
            <search-fields>lastname</search-fields>
        </search-filter>
        <search-filter>
            <name>Voornaam bevat</name>
            <search-fields>firstname</search-fields>
        </search-filter>
        <search-filter>
            <name>Gebruikersnaam bevat</name>
            <search-fields>username</search-fields>
        </search-filter>
    </command>
</list>

=== mmbase/mmbase/contributions/CMSContainer/cmsc/sitemanagement/src/webapp/editors/config/stylesheet/search_site_allowrel_stylesheet.xml
<?xml version="1.0"?>
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list role="allowrel" destination="stylesheet" minoccurs="0" maxoccurs="1">
	<title xml:lang="nl">Style Sheet</title>
	<title xml:lang="en">Style Sheet</title>
	<title xml:lang="zh">样式表</title>

	<item>
		<field ftype="data" name="title">
			<prompt xml:lang="en">Title</prompt>
			<prompt xml:lang="nl">Titel</prompt>
			<prompt xml:lang="zh">标题</prompt>
		</field>
		<field ftype="data" name="resource">
			<prompt xml:lang="en">Resource</prompt>
			<prompt xml:lang="nl">Style Sheet</prompt>
			<prompt xml:lang="zh">资源</prompt>
		</field>
	</item>
	
	<command name="search" nodepath="stylesheet" age="-1" fields="title" orderby="title">
		<prompt xml:lang="en">Search Style Sheet</prompt>
		<prompt xml:lang="nl">Zoek Style Sheet</prompt>
		<prompt xml:lang="zh">查找样式表</prompt>
		<search-filter>
			<name xml:lang="en">Title contains</name>
			<name xml:lang="nl">Titel bevat</name>
			<name xml:lang="zh">标题包含</name>
			<search-fields>[title]</search-fields>
		</search-filter>
	</command>

	<action type="create">
		<relation destinationtype="stylesheet" role="allowrel">
         <field name="allow">1</field>      
      </relation>
	</action>
</list>

=== mmbase/mmbase/contributions/CMSContainer_Portlets/portlets-teaser/src/webapp/editors/config/images/search_banners_imagerel_images.xml
<?xml version="1.0"?>
<!DOCTYPE list PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<list role="imagerel" destination="images" minoccurs="0" maxoccurs="*" orderby="field[@name='order']" ordertype="number">
	<title xml:lang="nl">Afbeelding</title>
	<title xml:lang="en">Image</title>
	
	<item displaytype="image">
	    <field name="title" dtrequired="true">
			<prompt xml:lang="en">Title</prompt>
			<prompt xml:lang="nl">Titel</prompt>
		</field>
	    <field name="description" ftype="text" rows="4">
			<prompt xml:lang="en">Description</prompt>
			<prompt xml:lang="nl">Omschrijving</prompt>
		</field>
	    <field name="handle" ftype="image">
			<prompt xml:lang="en">Image</prompt>
			<prompt xml:lang="nl">Afbeelding</prompt>
		</field>
	</item>
	
	<command name="search" nodepath="images" age="-1" fields="title,description">
		<prompt xml:lang="en">Search image</prompt>
		<prompt xml:lang="nl">Zoek afbeelding</prompt>
		<search-filter>
			<name xml:lang="en">Title contains</name>
			<name xml:lang="nl">Titel bevat</name>
			<search-fields>[title]</search-fields>
		</search-filter>
		<search-filter>
			<name xml:lang="en">Description contains</name>
			<name xml:lang="nl">Omschrijving bevat</name>
			<search-fields>[description]</search-fields>
		</search-filter>
	</command>
	
	<command name="insert" objectnumber="new">
		<prompt xml:lang="en">New</prompt>
		<prompt xml:lang="nl">Nieuw</prompt>
	</command>

	<action type="create">
		<relation role="imagerel">
			<field name="order">{sum(//relation[@role=&apos;imagerel&apos; and @lastitem=&apos;true&apos;]/field[@name=&apos;order&apos;])+{$pos}}</field>
			<object type="images" />
		</relation>
	</action>
</list>

=== mmbase/mmbase/contributions/CMSContainer_Portlets/portlets-dynamicforms/src/webapp/editors/config/option_lists/inputtypes.xml
<?xml version="1.0"?>
<!DOCTYPE optionlist PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<optionlist name="inputtypes">
   <option id="1">Textbox</option>
   <option id="2">Textarea</option>
   <option id="3">Hidden</option>
   <option id="4">Radio Button</option>
   <option id="5">Select</option>
   <option id="6">Checkbox</option>
   <option id="7">Attachment</option>
</optionlist>

=== mmbase/mmbase/contributions/CMSContainer/cmsc/sitemanagement/src/webapp/editors/config/site/edit_site.xml
<?xml version="1.0"?>
<!DOCTYPE form-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<form-schema id="edit_site">
	<title xml:lang="nl">Site</title>
	<title xml:lang="en">Site</title>

	<field name="stagingfragment" dtmaxlength="40"
		dtpattern="^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,38}[a-zA-Z0-9]$"
		dtrequired="true">
		<prompt xml:lang="en">Staging domain</prompt>
		<prompt xml:lang="nl">Staging domein</prompt>
	</field>
	<field name="urlfragment" dtmaxlength="40"
		dtpattern="^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,38}[a-zA-Z0-9]$"
		dtrequired="true">
		<prompt xml:lang="en">Live domain</prompt>
		<prompt xml:lang="nl">Live domein</prompt>
	</field>
	<field name="title" dtmaxlength="40" dtrequired="true">
		<prompt xml:lang="en">Title</prompt>
		<prompt xml:lang="nl">Titel</prompt>
	</field>
	<field name="description" dtmaxlength="1024" ftype="text" rows="3">
		<prompt xml:lang="en">Description</prompt>
		<prompt xml:lang="nl">Omschrijving</prompt>
	</field>
	<field name="inmenu" ftype="enum">
		<prompt xml:lang="en">In menu</prompt>
		<prompt xml:lang="nl">In menu</prompt>
		<optionlist select="boolean" />
	</field>
	<field name="secure" ftype="enum">
		<prompt xml:lang="en">Secure</prompt>
		<prompt xml:lang="nl">Beveiligd</prompt>
		<optionlist select="boolean" />
	</field>

	<field name="language" dtmaxlength="2"
>
		<prompt xml:lang="en">Language</prompt>
		<prompt xml:lang="nl">Taal</prompt>
	</field>
	<field name="creator" dtmaxlength="150">
		<prompt xml:lang="en">Creator</prompt>
		<prompt xml:lang="nl">Auteur</prompt>
	</field>
	<field name="publisher" dtmaxlength="150">
		<prompt xml:lang="en">Publisher</prompt>
		<prompt xml:lang="nl">Publicist</prompt>
	</field>
	<field name="source" dtmaxlength="150">
		<prompt xml:lang="en">Source</prompt>
		<prompt xml:lang="nl">Bronvermelding</prompt>
	</field>
	<field name="rights" dtmaxlength="150">
		<prompt xml:lang="en">Rights</prompt>
		<prompt xml:lang="nl">Rechten</prompt>
	</field>

	<list include="config/layout/search_page_layoutrel_layout.xml" />
	<list include="config/stylesheet/search_page_stylerel_stylesheet.xml" />
	<list include="config/images/search_page_namedrel_images.xml" />

	<list include="config/typedef/search_site_allowrel_typedef.xml" />
</form-schema>

=== mmbase/mmbase/contributions/didactor2/src/faq/templates/editwizards/data/config/faq/rootfaqnodes.xml
<?xml version="1.0"?>
<!DOCTYPE wizard-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<wizard-schema id="empty">
  <title>FAQ Editor</title>

  <action type="create">
    <object type="faqnodes" />
  </action>

  <action type="load">
    <object type="faqnodes"/>
    <relation destinationtype="faqitems" role="related"/>
    <relation destinationtype="educations" role="related"/>
    <relation destinationtype="roles" role="related"/>
    <relation destination="paragraphs" role="posrel">
      <object>
        <relation destination="attachments" role="posrel" />
        <relation destination="images" role="pos2rel" />
        <relation destination="urls" role="posrel" />
      </object>
    </relation>
  </action>

  <action type="delete" />

  <lists>
    <optionlist include="config/option_list/images_position.xml" />
    <optionlist include="config/option_list/boolean.xml" />
    <optionlist include="config/option_list/layout_ext.xml" />
    <optionlist include="config/option_list/images_position.xml" />
  </lists>

  <steps>
    <step form-schema="step1" />
    <step form-schema="step2" />
  </steps>

  <form-schema id="step1">
    <title>Naam</title>
    <field name="name" >
      <prompt>Naam</prompt>
    </field>
    <field name="body" ftype="html">
      <prompt>Tekst</prompt>
    </field>
    <list role="related" destination="faqitems" minoccurs="0" maxoccurs="*">
      <title>FAQ Item</title>
      <!-- Show the 'item' in a list (the object) -->
      <item>
        <field name="question">
          <prompt>Vraag</prompt>
          <description></description>
        </field>
        <field wizardname="config/faq/faqitems" ftype="startwizard" />
      </item>
      <command name="startwizard" inline="true" wizardname="config/faq/faqitems" objectnumber="new" />
      <command name="search" nodepath="faqitems" fields="question" age="-1">
        <prompt>Search FAQ Item</prompt>
        <search-filter>
          <name>vraag bevat</name>
          <search-fields>question</search-fields>
        </search-filter>
      </command>
      <action type="create">
        <relation destinationtype="faqitems" role="related" >
          <object type="faqitems"/>
        </relation>
      </action>
      <action type="add">
        <relation destinationtype="faqitems" role="related" />
      </action>
    </list>
    <list role="related" destination="educations" minoccurs="0" maxoccurs="*">
      <title>Bijbehorende Opleidingen</title>
      <!-- Show the 'item' in a list (the object) -->
      <item>
        <field name="name">
          <prompt>Name</prompt>
          <description></description>
        </field>
        <field wizardname="config/education/educations" ftype="startwizard" />
      </item>
      <command name="startwizard" inline="true" wizardname="config/education/educations" objectnumber="new" />
      <command name="search" nodepath="educations" fields="name" age="-1">
        <prompt>Naam</prompt>
        <search-filter>
          <name>naam bevat</name>
          <search-fields>name</search-fields>
        </search-filter>
      </command>
      <action type="create">
        <relation destinationtype="educations" role="related" >
          <object type="educations"/>
        </relation>
      </action>
      <action type="add">
        <relation destinationtype="educations" role="related" />
      </action>
    </list>
    <list role="related" destination="roles" minoccurs="0" maxoccurs="*">
      <title>Bijbehorende Rol</title>
      <!-- Show the 'item' in a list (the object) -->
      <item>
        <field name="name">
          <prompt>Naam</prompt>
          <description></description>
        </field>
        <field wizardname="config/role/roles" ftype="startwizard" />
      </item>
      <command name="startwizard" inline="true" wizardname="config/role/roles" objectnumber="new" />
      <command name="search" nodepath="roles" fields="name" age="-1">
        <prompt>Search Rol</prompt>
        <search-filter>
          <name>naam bevat</name>
          <search-fields>name</search-fields>
        </search-filter>
      </command>
      <action type="create">
        <relation destinationtype="roles" role="related" >
          <object type="roles"/>
        </relation>
      </action>
      <action type="add">
        <relation destinationtype="roles" role="related" />
      </action>
    </list>
  </form-schema>

  <form-schema id="step2">
    <title xml:lang="nl">Alineas invoeren</title>
    <title xml:lang="en">Enter paragraphs</title>

    <field name="name" ftype="data"/>
    <list extends="config/paragraphs/add_paragraphs_posrel.xml"/>
  </form-schema>
</wizard-schema>

=== mmbase/mmbase/contributions/CMSContainer/cmsc/utilities/src/webapp/editors/config/properties/edit_properties.xml
<?xml version="1.0"?>
<!DOCTYPE form-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<form-schema id="edit_properties">
	<title xml:lang="nl">Instelling</title>
	<title xml:lang="en">Property</title>

	<field name="key" dtmaxlength="40">
		<prompt xml:lang="en">Key</prompt>
		<prompt xml:lang="nl">Naam</prompt>
	</field>
	<field name="description" dtmaxlength="1024" ftype="text" rows="3">
		<prompt xml:lang="en">Description</prompt>
		<prompt xml:lang="nl">Omschrijving</prompt>
	</field>
	<field name="value" dtmaxlength="255" ftype="text" rows="3">
		<prompt xml:lang="en">Value</prompt>
		<prompt xml:lang="nl">Waarde</prompt>
	</field>
	<field name="prod" dtmaxlength="255" ftype="text" rows="3">
		<prompt xml:lang="en">Production</prompt>
		<prompt xml:lang="nl">Productie</prompt>
	</field>
	<field name="preprod" dtmaxlength="255" ftype="text" rows="3">
		<prompt xml:lang="en">Acceptance</prompt>
		<prompt xml:lang="nl">Acceptatie</prompt>
	</field>
	<field name="test" dtmaxlength="255" ftype="text" rows="3">
		<prompt xml:lang="en">Test</prompt>
		<prompt xml:lang="nl">Test</prompt>
	</field>
	<field name="dev" dtmaxlength="255" ftype="text" rows="3">
		<prompt xml:lang="en">Development</prompt>
		<prompt xml:lang="nl">Development</prompt>
	</field>
</form-schema>

=== mmbase/mmbase/applications/editwizard/blocks/samples/news_blocks.xml
<?xml version="1.0"?>
<!DOCTYPE wizard-schema PUBLIC "-//MMBase/DTD editwizard 1.0//EN" "http://www.mmbase.org/dtd/wizard-schema_1_0.dtd">
<wizard-schema id="empty">
  <title xml:lang="nl">Voer hier de wizard titel in</title>
  <title xml:lang="en">Enter Wizard Title Here</title>

  <action type="create">
    <object type="news" />
  </action>

  <action type="delete" />

  <action type="load">
    <blocks classification="test.editwizards" render="head" />
  </action>

  <form-schema id="step1">
    <title>Enter form title here</title>
    <title xml:lang="nl">Voer hier de formulier titel in</title>

    <field name="title" />
    <field name="subtitle" />

    <field name="intro" />

    <field name="body" ftype="html" rows="8" />
    <field name="date" />

  </form-schema>

  <blocks classification="test.editwizards" />

</wizard-schema>
