=== mmbase/mmbase/contributions/lucene/src/org/mmbase/module/lucene/resources/luceneindex_2_0.dtd
<!ELEMENT luceneindex (index*)>

<!ELEMENT index (list*)>
<!ATTLIST index name NMTOKEN #IMPLIED>
<!ATTLIST index optimize NMTOKEN #IMPLIED>

<!ELEMENT list (constraint*,field*, related*)>
<!ATTLIST list type NMTOKEN #IMPLIED>
<!ATTLIST list path NMTOKEN #IMPLIED>
<!ATTLIST list searchdirs NMTOKEN #IMPLIED>
<!ATTLIST list element NMTOKEN #IMPLIED>
<!ATTLIST list optimize NMTOKEN #IMPLIED>

<!ELEMENT related (constraint*,field*, related*)>
<!ATTLIST related type NMTOKEN #IMPLIED>
<!ATTLIST related path NMTOKEN #IMPLIED>
<!ATTLIST related searchdirs NMTOKEN #IMPLIED>
<!ATTLIST related element NMTOKEN #IMPLIED>
<!ATTLIST related optimize NMTOKEN #IMPLIED>

<!ELEMENT constraint EMPTY>
<!ATTLIST constraint field NMTOKEN #IMPLIED>
<!ATTLIST constraint value NMTOKEN #IMPLIED>
<!ATTLIST constraint operator NMTOKEN #IMPLIED>
<!ATTLIST constraint value2 NMTOKEN #IMPLIED>
<!ATTLIST constraint field2 NMTOKEN #IMPLIED>
<!ATTLIST constraint part NMTOKEN #IMPLIED>
<!ATTLIST constraint casesensitive NMTOKEN #IMPLIED>
<!ATTLIST constraint inverse NMTOKEN #IMPLIED>

<!ELEMENT field (#PCDATA)>
<!ATTLIST field name NMTOKEN #REQUIRED>
<!ATTLIST field alias NMTOKEN #IMPLIED>
<!ATTLIST field keyword NMTOKEN #IMPLIED>
<!ATTLIST field store NMTOKEN #IMPLIED>
<!ATTLIST field password NMTOKEN #IMPLIED>

=== mmbase/mmbase/mmbase/trunk/contributions/lucene/config/utils/luceneindex.xml
<?xml version="1.0"?>
<!DOCTYPE luceneindex PUBLIC "-//MMBase//DTD luceneindex config 2.0//EN" "http://www.mmbase.org/dtd/luceneindex_2_0.dtd">
<luceneindex>
  <index>
    <query type="documents">
      <field name="title" />
      <field name="subtitle" />
      <field name="intro" />
      <field name="body" />
      <field name="begin" />
      <field name="end" />
      <field name="visible" />
      <field name="handle" />
      <field name="documentnummer" />
    </query>
    <query path="cases,documents" element="cases">
      <field name="cases.title" />
      <field name="cases.subtitle" />
      <field name="cases.intro" />
      <field name="cases.body" />
      <field name="documents.title" />
      <field name="documents.subtitle" />
      <field name="documents.documentnummer" />
      <field name="cases.begin" alias="begin" />
      <field name="cases.end" alias="end" />
      <field name="cases.visible" alias="visible" />
      <field name="cases.casusnummer" />
    </query>
  </index>
</luceneindex>
